### ISSUE TITLE
Logistics Wizard Toolchain does not work

### ISSUE THREAD

**Issue by maneuma** [IBM-Cloud/logistics-wizard#265]
When I click on the link create toolchain I get this error

Template Error

Repository not found.
Github repo not found: https://github.com/IBM-Cloud/logistics-wizard-toolchain

Please let me know anyone has any ideas.  Thanks for the help.

**Comment by data-henrik** [comment]
@maneuma could you add details on what steps you performed? The repo exists and we would need to track down what caused the error you were seeing

**Comment by rvennam** [comment]
@data-henrik I am able to recreate this by clicking on `Create Toolchain` button

**Comment by maneuma** [comment]
Good morning.  Thanks for the help on this.  I go to this url.  https://github.com/IBM-Cloud/logistics-wizard-toolchain   I go to step 5 and click on the create toolchain button.   And then I get this error.  Template Error
Repository not found.
Github repo not found: https://github.com/IBM-Cloud/logistics-wizard-toolchain

Please let me know if you need anymore information.  Thanks

**Comment by data-henrik** [comment]
Similar to @rvennam I can confirm the error. From a first investigation, this is a toolchain problem and someone from the toolchain team is looking into it.

**Comment by data-henrik** [comment]
It should work again, closing this issue.

**Comment by maneuma** [comment]
Hi.  Thanks for the help on this.  I got farther this time.   four apps were deployed.  dev-logistics-wizard-toolchain controller and erp, logistics-wizard-toolchain controller and erp.  The logistics-wizard  recommendation and webui did not seem to be deployed by the toolchain wizard.  Any ideas on what I did wrong?  Thanks
